# Generated by Django 4.0.5 on 2022-07-20 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20)),
                ('idade', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('nascimento', models.DateField(null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nacionalidade', models.CharField(default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20)),
                ('idade', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('nascimento', models.DateField(null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nacionalidade', models.CharField(default='', max_length=20)),
                ('escolaridade', models.CharField(choices=[('0-4', '0-4'), ('5-9', '5-9'), ('10-12', '10-12'), ('12+', '12+')], default='0-9', max_length=20)),
                ('regime', models.CharField(choices=[('Online', 'Online'), ('Presencial', 'Presencial'), ('Misto', 'Misto')], default='Online', max_length=20)),
                ('localizacao', models.CharField(default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doenca', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('diagnostico', models.CharField(default='', max_length=20)),
                ('localizacao', models.CharField(default='', max_length=20)),
                ('escolaridade', models.CharField(choices=[('0-4', '0-4'), ('5-9', '5-9'), ('10-12', '10-12'), ('12+', '12+')], default='0-9', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoCog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20)),
                ('idade', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('nascimento', models.DateField(null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nacionalidade', models.CharField(default='', max_length=20)),
                ('avaliador', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cuidadores', models.ManyToManyField(blank=True, related_name='participantes', to='diario.cuidador')),
                ('diagnosticos', models.ManyToManyField(related_name='participantes', to='diario.doenca')),
                ('grupoCog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='diario.grupocog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('estado', models.CharField(blank=True, choices=[('PR', 'Por realizar'), ('R', 'Realizado')], default='PR', max_length=20, null=True)),
                ('regime', models.CharField(blank=True, choices=[('P', 'Presencial'), ('O', 'Online'), ('M', 'Misto')], default='P', max_length=20, null=True)),
                ('numeroSessao', models.CharField(blank=True, max_length=10, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('introducao', models.TextField(blank=True, max_length=1000, null=True)),
                ('instrucoes', models.TextField(blank=True, max_length=1000, null=True)),
                ('tema', models.CharField(blank=True, max_length=1000, null=True)),
                ('dinamizadores', models.CharField(blank=True, max_length=1000, null=True)),
                ('componentes', models.CharField(blank=True, max_length=1000, null=True)),
                ('grupos', models.ManyToManyField(blank=True, related_name='sessoes', to='diario.grupocare')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(blank=True, max_length=1, null=True)),
                ('respostas', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('tipoSessao', models.CharField(blank=True, choices=[('PR', 'Protocolo'), ('CG', 'Cog'), ('CR', 'Care')], default='CR', max_length=20, null=True)),
                ('present', models.BooleanField(default=False)),
                ('faltou', models.BooleanField(default=False)),
                ('mode', models.CharField(blank=True, choices=[('P', 'Presencial'), ('O', 'Online')], default='P', max_length=20, null=True)),
                ('withApp', models.BooleanField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='diario.participante')),
                ('sessao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessao', to='diario.sessao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartilhaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.grupocare')),
            ],
        ),
        migrations.CreateModel(
            name='Partilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partilha', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
            ],
        ),
        migrations.AddField(
            model_name='participante',
            name='referenciacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.reference'),
        ),
        migrations.CreateModel(
            name='NotaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notaGrupo', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.grupocare')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Atividades', 'Atividades'), ('Gerais', 'Gerais'), ('Sessão', 'Sessão')], default='Gerais', max_length=20)),
                ('tituloNota', models.CharField(default='', max_length=20)),
                ('nota', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20)),
                ('idade', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('nascimento', models.DateField(null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nacionalidade', models.CharField(default='', max_length=20)),
                ('grupoCare', models.ManyToManyField(blank=True, related_name='mentores', to='diario.grupocare')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformacoesGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.grupocare')),
            ],
        ),
        migrations.CreateModel(
            name='Informacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacoes', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
            ],
        ),
        migrations.AddField(
            model_name='grupocare',
            name='referenciacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.reference'),
        ),
        migrations.CreateModel(
            name='GrupoAvalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.avaliador')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facilitador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20)),
                ('idade', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('nascimento', models.DateField(null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nacionalidade', models.CharField(default='', max_length=20)),
                ('grupoCog', models.ManyToManyField(blank=True, related_name='facilitadores', to='diario.grupocog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('materiais', models.CharField(blank=True, max_length=1000, null=True)),
                ('fase', models.CharField(blank=True, choices=[('I', 'Inicial'), ('D', 'Desenvolvimento'), ('F', 'Final')], max_length=10, null=True)),
                ('duracao', models.CharField(blank=True, max_length=10, null=True)),
                ('atividade', models.TextField(blank=True, max_length=1000, null=True)),
                ('objetivo', models.TextField(blank=True, max_length=1000, null=True)),
                ('sessoes', models.ManyToManyField(related_name='exercicios', to='diario.sessao')),
            ],
        ),
        migrations.CreateModel(
            name='DinamizadorConvidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20)),
                ('idade', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('nascimento', models.DateField(null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nacionalidade', models.CharField(default='', max_length=20)),
                ('funcao', models.CharField(default='', max_length=20)),
                ('grupoCare', models.ManyToManyField(blank=True, related_name='dinamizadores', to='diario.grupocare')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cuidador',
            name='grupoCare',
            field=models.ManyToManyField(blank=True, related_name='cuidadores', to='diario.grupocare'),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='referenciacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.reference'),
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20)),
                ('idade', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('nascimento', models.DateField(null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nacionalidade', models.CharField(default='', max_length=20)),
                ('grupoCog', models.ManyToManyField(blank=True, related_name='auxiliares', to='diario.grupocog')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
