# Generated by Django 4.0.5 on 2022-07-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='first_name',
            field=models.CharField(default='a', max_length=15),
        ),
    ]
