# Generated by Django 4.0.5 on 2022-07-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_participante_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='last_name',
            field=models.CharField(default='b', max_length=15),
        ),
    ]
