# Generated by Django 4.0.5 on 2022-07-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0003_participante_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='last_name',
        ),
    ]
