# Generated by Django 4.0.3 on 2022-10-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0005_participante_escolaridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='escolaridade',
            field=models.CharField(choices=[('Analfabeto', 'Analfabeto'), ('1-4', '1-4'), ('5-10', '5-10'), ('11+', '11+')], default='1-4', max_length=20),
        ),
    ]
