# Generated by Django 4.0.3 on 2022-10-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0006_alter_participante_escolaridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='agregadoFamiliar',
            field=models.CharField(blank=True, choices=[('Vive sozinho(a)', 'Vive sozinho(a)'), ('Vive com o cônjuge', 'Vive com o cônjuge'), ('Vive com os filhos', 'Vive com os filhos'), ('Vive com terceiros', 'Vive com terceiros'), ('Vive com o cônjuge e terceiros', 'Vive com o cônjuge e terceiros'), ('Vive com os pais', 'Vive com os pais')], default='Vive sozinho(a)', max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='autoAvaliacaoEstadoSaude',
            field=models.CharField(blank=True, choices=[('Muito mau', 'Muito mau'), ('Mau', 'Mau'), ('Nem mau nem bom', 'Nem mau nem bom'), ('Bom', 'Bom'), ('Muito bom', 'Muito bom')], default='Nem mau nem bom', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='estadoCivil',
            field=models.CharField(blank=True, choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a) ou a viver como tal', 'Casado(a) ou a viver como tal'), ('Viúvo(a)', 'Viúvo(a)'), ('Divorciado(a) ou separado(a)', 'Divorciado(a) ou separado(a)')], default='Solteiro(a)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='nrFilhos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='opSituacaoLaboral',
            field=models.CharField(blank=True, choices=[('Empregado(a)', 'Empregado(a)'), ('Desempregado(a)', 'Desempregado(a)'), ('Reformado(a)', 'Reformado(a)'), ('Doméstica', 'Doméstica'), ('Estudante', 'Estudante')], default='Reformado(a)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='profissaoPrincipal',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='residencia',
            field=models.CharField(blank=True, choices=[('Urbana', 'Urbana'), ('Rural', 'Rural')], default='Urbana', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='situacaoEconomica',
            field=models.CharField(blank=True, choices=[('Muito satisfatória', 'Muito satisfatória'), ('Satisfatória', 'Satisfatória'), ('Pouco satisfatória', 'Pouco satisfatória'), ('Nada satisfatória', 'Nada satisfatória')], default='Satisfatória', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='temFilhos',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
