# Generated by Django 4.0.3 on 2022-10-02 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0007_participante_agregadofamiliar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doenca',
            old_name='doenca',
            new_name='nome',
        ),
    ]
