# Generated by Django 4.0.3 on 2022-10-02 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0008_rename_doenca_doenca_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participante',
            old_name='opSituacaoLaboral',
            new_name='situacaoLaboral',
        ),
    ]
