# Generated by Django 4.0.5 on 2022-07-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0002_alter_question_evaluation_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(default=1),
        ),
    ]
