# Generated by Django 4.0.5 on 2022-07-20 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diario', '0001_initial'),
        ('protocolo', '0004_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='doctor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='patient',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.participante'),
        ),
    ]
