# Generated by Django 3.1.2 on 2022-04-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0004_auto_20220407_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasDeAvaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(blank=True, max_length=280)),
                ('ordem', models.IntegerField()),
                ('partes', models.ManyToManyField(to='protocolo.Parte')),
            ],
        ),
    ]
