# Generated by Django 4.0.5 on 2022-07-25 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0005_resolution_doctor_alter_resolution_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='instruction',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='TextInputAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds', models.IntegerField(blank=True, default=0, null=True)),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TIAnswer', to='protocolo.answer')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoicesCheckbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.IntegerField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MCCAnswer', to='protocolo.answer')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CheckBoxChoice', to='protocolo.possibleanswer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
