# Generated by Django 3.1.2 on 2022-04-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0005_areasdeavaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='parte',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
