# Generated by Django 3.1.2 on 2022-04-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0007_auto_20220407_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='parte',
            field=models.IntegerField(null=True),
        ),
    ]
