# Generated by Django 4.0.5 on 2022-08-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0007_question_pdf_page_alter_question_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibleanswer',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='possible_answers_images/'),
        ),
    ]
