# Generated by Django 3.1.2 on 2022-04-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0008_auto_20220407_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='parte',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
