# Generated by Django 3.1.2 on 2022-04-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0009_auto_20220407_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areasdeavaliacao',
            name='nome',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='parte',
            name='nome',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='nome',
            field=models.CharField(max_length=55),
        ),
    ]
