# Generated by Django 3.1.2 on 2022-04-07 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0010_auto_20220407_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areasdeavaliacao',
            name='partes',
            field=models.ManyToManyField(default=None, related_name='partes', to='protocolo.Parte'),
        ),
        migrations.AlterField(
            model_name='parte',
            name='protocolo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='protocolos', to='protocolo.protocolo'),
        ),
    ]
