# Generated by Django 4.0.5 on 2022-09-20 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0010_instrument_area_m2m_alter_instrument_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='area',
        ),
    ]
