# Generated by Django 4.0.5 on 2022-09-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0011_remove_instrument_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='area_m2m',
            new_name='area',
        ),
    ]
