# Generated by Django 4.0.3 on 2022-10-01 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0012_rename_area_m2m_instrument_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='tooltip',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
