# Generated by Django 4.0.3 on 2022-04-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0013_part_part_alter_area_id_alter_dimension_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='parts',
            new_name='part',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='part',
            new_name='part_number',
        ),
    ]
