# Generated by Django 3.1.2 on 2022-04-16 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0015_auto_20220415_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='instruction',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(max_length=500)),
                ('multiple_choice_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocolo.possibleanswers')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocolo.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='helping_images',
            field=models.ManyToManyField(default=None, related_name='images', to='protocolo.QuestionImages'),
        ),
        migrations.AddField(
            model_name='question',
            name='possible_answers',
            field=models.ManyToManyField(blank=True, default=None, related_name='possible_answers', to='protocolo.PossibleAnswers'),
        ),
    ]
