# Generated by Django 3.1.2 on 2022-04-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0016_auto_20220416_1656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PossibleAnswers',
            new_name='PossibleAnswer',
        ),
        migrations.RenameModel(
            old_name='QuestionImages',
            new_name='QuestionImage',
        ),
    ]
