# Generated by Django 3.1.2 on 2022-04-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0017_auto_20220416_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimage',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
