# Generated by Django 3.1.2 on 2022-04-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0019_auto_20220416_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='possibleanswer',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='helping_images',
            field=models.ManyToManyField(blank=True, default=None, related_name='images', to='protocolo.QuestionImage'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
