# Generated by Django 3.1.2 on 2022-04-18 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protocolo', '0020_auto_20220416_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('answers', models.ManyToManyField(blank=True, default=None, related_name='answers', to='protocolo.Answer')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocolo.part')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
