# Generated by Django 3.1.2 on 2022-04-18 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0021_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='instrument',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='protocolo.instrument'),
        ),
    ]
