# Generated by Django 3.1.2 on 2022-04-18 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0022_dimension_instrument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimension',
            name='area',
        ),
        migrations.AlterField(
            model_name='dimension',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocolo.instrument'),
        ),
    ]
